services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yaocihuatl-backend
    environment:
      APP_ENV: local
      PORT: 8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/apps/dashboard
      dockerfile: Dockerfile
    container_name: yaocihuatl-frontend
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
